### ISSUE TITLE
Event Listeners + Large Objects Performance issue

### ISSUE THREAD

**Issue by amammay** [msalehisedeh/differentiate#1]
On larger objects it seems like there are way to many events being captured when using the scroll wheel. I suspect that the (mouseout) and (mouseover) event listeners are suspect.

To replicate, just put some giant json objects (500+ nodes) into the diff and try to use the scroll wheel on your mouse. You will notice that its very laggy, but if you drag the scroll bar its pretty smooth. 

For the meantime in my usecase i am having zone.js black list those events.

**Comment by msalehisedeh** [comment]
Thanks Amammay. I will look into it as soon as i can. Will keep you posted asap.

**Comment by msalehisedeh** [comment]
Yes. I see a lag on showing hover. In order to hover on both sides, i issue an event and based on that hover the same row on the opposite side. I will see if I can find a solution for it.

**Comment by msalehisedeh** [comment]
Thank you Amammay for pointing out the problem. It is now fixed. Problem was manifestation of having mouse over method on root object and all subsequent children of children of ...
Solution was to make sure to only have mouse over on one level and apply prevent default and stop propagation on the event inside event handler.
Appreciate it if you keep pointing out issues found.

**Comment by amammay** [comment]
no problem @msalehisedeh ! Thank you for the quick response! As my project continues to grow ill give feedback when i receive it!
