### ISSUE TITLE
Inaccurate diff count

### ISSUE THREAD

**Issue by rawatanimesh** [msalehisedeh/differentiate#10]
Can we have a feature to get accurate diff count. This can be in terms of fields/values added, deleted or modified. 
Currently we just get an array with diff count which also does not look accurate when compared to differences between two JSON.

Attaching screenshot for reference. We have multiple changes in key-values other than addition and deletion. But the dff count shows 3. 

<img width="959" alt="Capture" src="https://user-images.githubusercontent.com/25823744/110639525-d2d31c80-81d5-11eb-856f-08c021e4cddd.PNG">

**Comment by msalehisedeh** [comment]
please let me know what you see missing. currently the difference shown is on added (+) or deleted (-) or changed (~).
What do you have in mind that would make it a better tool for you?

**Comment by rawatanimesh** [comment]
On the UI, yes we are showing the differences using '+', '-' or '~'. I am talking about the function 'ondifference' which gives an array with value of diff count. This count is different from actual number of differences between two objects. Attaching the screenshot with highlights.
In the screenshot, the 'ondifference' function shows diff count of 3, but differences are more (highlighted)  
<img width="941" alt="Capture" src="https://user-images.githubusercontent.com/25823744/110779906-1be4a880-828a-11eb-9c56-4822edd27d0c.PNG">

Current output is: Diff Count = 3
Suggested output: Changed= 4, Added= 1, Deleted = 1

**Comment by msalehisedeh** [comment]
will do. probably will issue another output to give detailed info in order to keep compatibility for any other project that already using this.

**Comment by msalehisedeh** [comment]
will update code soon. Sorry for the long delay

**Comment by msalehisedeh** [comment]
resolved with version 3.1.0

**Comment by msalehisedeh** [comment]
resolved by correcting color
