### ISSUE TITLE
Why not standalone?

### ISSUE THREAD

**Issue by henryruhs** [msalehisedeh/differentiate#11]
May I ask why you thought it is a good idea to empty the `index.html` and `main.ts` to prevent someone using `ng serve` on that project? There are issues with the `polyfill.js` as of missing `core-js/es7/reflect` and `angular.json` that linked to `styles.css` instead of `styles.scss`.

I got it running in the end but why making it that hard to developers?

**Comment by msalehisedeh** [comment]
I really do not recall the reason for doing this other than trying to keep this as an npm and not a standalone. But, I'll keep your feedback under consideration and will include it in my next update to angular 10. Will do it as soon as I am free from work-related issues.
Thank you very much for your valuable feedback.

**Comment by henryruhs** [comment]
Okay, I close that issue for now...
