### ISSUE TITLE
Inaccurate difference representation

### ISSUE THREAD

**Issue by rawatanimesh** [msalehisedeh/differentiate#13]
Hi Sedeh,

If I add a key-value at the root level of a object and another key-value at a nested level, I see a difference in representation. One is shown in green, and other one is being shown in red. This is very confusing and misrepresents the differences. Attaching screenshot for your reference. 

<img width="483" alt="Capture" src="https://user-images.githubusercontent.com/25823744/112652840-db814f00-8e73-11eb-8025-551c7734cdbf.PNG">

Here I added key 'Bumbulbee' (showing in green) at root level and 'new prop2' (showing in red) at a nested level in the same object on left hand side. They are being shown in different manner. Logically this is inconsistent. Please check.

**Comment by msalehisedeh** [comment]
thanks. will furnish a fix as soon as I upgrade Angular to a higher version.

**Comment by msalehisedeh** [comment]
fixed with version 3.2.0
