### ISSUE TITLE
when empty string, I see following error..

### ISSUE THREAD

**Issue by adornala** [msalehisedeh/differentiate#2]
TypeError: node.value.toUpperCase is not a function

node.value = ""

https://github.com/msalehisedeh/differentiate/blob/9ca73ea0b7e08884f64c2d3101a22a9748d36109/src/app/differentiate/components/differentiate.component.ts#L210

**Comment by msalehisedeh** [comment]
resolved in 2.3.1 version

**Comment by adornala** [comment]
Resolved.. Thank you @msalehisedeh
