### ISSUE TITLE
documentation - import statement is incorrect

### ISSUE THREAD

**Issue by saarea** [msalehisedeh/differentiate#4]
`import { DifferentiateModule } from 'differentiate';`

should be 

`import { DifferentiateModule } from '@sedeh/differentiate';`

**Comment by msalehisedeh** [comment]
thank you very much for pointing it out. I fixed it in READ_ME file. Please let me know if there is anything I can modify to make this component do a better job accomodating your needs.

**Comment by msalehisedeh** [comment]
closing as it is fixed.
