### ISSUE TITLE
When  there is 0 in json it is  displayed as change even if there were not any  change done

### ISSUE THREAD

**Issue by TarasBek** [msalehisedeh/differentiate#42]
does anyone know how to fix that?
![Screenshot 2023-12-20 123411](https://github.com/msalehisedeh/differentiate/assets/74894953/51ad1a3c-a17b-4523-a6d7-15ed981689f1)

**Comment by msalehisedeh** [comment]
Please replace 
            value: jsonValue,
width
            value: String(jsonValue),
in line 151 in file differentiate.component.ts

I will include the change later on with an angular upgrade

**Comment by msalehisedeh** [comment]
resolved in version 3.1.0
