### ISSUE TITLE
Some bugs after update to v3.2.1

### ISSUE THREAD

**Issue by TarasBek** [msalehisedeh/differentiate#57]
Hi Masoud, big  thank for updating angular verstion and fixing some bugs.
After using tool with  version 3.2.1 i found some bugs that are blocking some fundamental functionality
Here are the identified bugs:

1. Upon opening the application with the differentiate component, I noticed a loader appearing even before any interaction with the tool.
2. I have to click twice to obtain results from the component.
3. Even after the results are loaded in the differentiate component, the loader persists until I hover over it.

To provide you with a clearer understanding of these issues, I've created a concise example that you can easily test. Please visit the following link: [StackBlitz Example](https://stackblitz.com/edit/stackblitz-starters-hdwb1d)
Please  can you  look  at it?

If there is any additional information or support required from my end, feel free to reach out to me via LinkedIn: [My LinkedIn Profile](https://www.linkedin.com/in/taras-bek-7bb89621b/).

Best regards,
Taras

**Comment by msalehisedeh** [comment]
Thanks. I will look into this. Thank you very much for reporting it 
     

-----Original Message-----

From: Taras ***@***.***>
To: msalehisedeh ***@***.***>
Cc: Subscribed ***@***.***>
Date: Wednesday, 24 January 2024 7:37 AM PST
Subject: [msalehisedeh/differentiate] Some bugs after update to v3.2.1 (Issue #57)

 

  Hi Masoud, big thank for updating angular verstion and fixing some bugs.
After using tool with version 3.2.1 i found some bugs that are blocking some fundamental functionality
Here are the identified bugs:  
  1. Upon opening the application with the differentiate component, I noticed a loader appearing even before any interaction with the tool. 
  2. I have to click twice to obtain results from the component. 
  3. Even after the results are loaded in the differentiate component, the loader persists until I hover over it.  To provide you with a clearer understanding of these issues, I've created a concise example that you can easily test. Please visit the following link: StackBlitz Example
Please can you look at it? If there is any additional information or support required from my end, feel free to reach out to me via LinkedIn: My LinkedIn Profile. Best regards,
Taras —

**Comment by msalehisedeh** [comment]
can you look and see the difference between your example nd mine?
https://stackblitz.com/edit/diffrenciate?file=src%2Fapp%2Fapp.component.ts

Also,  i see that you are using the actual differentiate code in your example instead of pulling @sedeh/differentiate.

**Comment by msalehisedeh** [comment]
updated code trying to default the left side and right side to undefined like your example. please try version 3.2.2 
I tried to update it in. the fork of your example but it keeps spinning. please try it on your side and let me know
I've updated my sample. Still i cannot reproduce your issue with the default values being undefined

**Comment by TarasBek** [comment]
I have tested new version in my example and unfortunately, the same 3 problems remain for me

**Comment by msalehisedeh** [comment]
I just ran your test sample and I can not see the loader at first. So item 1 in your reporting is fixed. 
i click twice and the loader will show as per design. So item 2 of your report needs to be resolved.  
For item 3 in your report, i am using a default period for timeout because the JSON  i have in my example is a bit larger than yours. so if you think the spinner time could be problematic, the only choice to resolve it is for me to allow the user to choose an appropriate delay

**Comment by msalehisedeh** [comment]
please use 3.2.3
not sure why your example item 2, 3 are not resolving. it is better than before and thanks to your request is more interactive in my example

**Comment by TarasBek** [comment]
Hi Masoud, i have properly tested your new version, and  everything  is looking good
Thank you very much for your fast response and for fixing it. I will close this issue now.

**Comment by msalehisedeh** [comment]
Thank you TarasBek. please try v3.3.3
Because of your help identifying issues, this library has become a lot better than before.
